language: node_js
node_js:
- 6.9.1
notifications:
  email:
    recipients:
    - biscayne3@gmail.com
    on_failure: always
    on_success: always

branches:
  only:
  - master
  - dev

install: 
- nvm install 8
- npm i

before_install:
- chmod +x scripts/docker_push.sh

script:
- npm run docker-build 

deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: master 

after_deploy:
- echo "Deployment was done"
